export enum SERVER_EVENTS {
    LOGOUT = "LOGOUT",
    UPDATE_ACTIVE_USERS = "UPDATE_ACTIVE_USERS"
}
export enum TEMPLATE_TABLES {
    FASAD = "fasad"
}

export enum DetailNames {
    WARDROBE_ROOF = 'WARDROBE_ROOF',
    WARDROBE_STAND = 'WARDROBE_STAND',
    WARDROBE_INNER_STAND = 'WARDROBE_INNER_STAND',
    WARDROBE_SHELF = 'WARDROBE_SHELF',
    WARDROBE_SHELFPLAT = 'WARDROBE_SHELFPLAT',
    WARDROBE_PILLAR = 'WARDROBE_PILLAR',
}