
export enum SpecItem {
    DSP10 = 1,
    Mirror = 2,
    Arakal = 3,
    Hydro = 4,
    Lacobel = 5,
    Ritrama = 6,
    Armirovka = 7,
    FMPPaper = 8,
    FMPGlass = 9,
    Paint = 10,
    EVA = 11,
    Uplot = 12,
    ProfileSoed = 13,
    ProfileVert = 14,
    ProfileHorTop = 15,
    ProfileHorBottom = 16,
    Roliki = 17,
    RolikiBavaria = 18,
    DSP16 = 19,
    DVP = 20,
    Kromka2 = 21,
    Kromka045 = 22,
    Glue = 23,
    Leg = 24,
    Confirmat = 25,
    ZagConfirmat = 26,
    ZagMinifix = 27,
    Minifix = 28,
    Nails = 29,
    PlankaDVP = 30,
    Trempel = 31,
    Truba = 32,
    Flanec = 33,
    Samorez16 = 34,
    StyagkaM6 = 35,
    NapravTop = 36,
    NapravBottom = 37,
    Stopor = 38,
    ConfKluch = 39,
    Box = 40,
    Streich = 41,
    Karton = 42,
    Skotch = 43,
    UplotSoedBavaria = 44,
    Brush = 45,
    BrushBavariaWhite = 46,
    Samorez30 = 47,
    Telescope250 = 48,
    Telescope300 = 49,
    Telescope350 = 50,
    Telescope400 = 51,
    Telescope450 = 52,
    Telescope500 = 53,
    Telescope550 = 54,
    Lamp = 55,
    Kromka1 = 56,
    Kromka06 = 57,
    Kromka08 = 58,
    BrushBavariaBrown = 59,
    BrushBavariaGray = 60,
    BrushBavariaBlack = 61,
}

export enum CORPUS_SPECS {
    CORPUS = "corpus",
    EXT_TEL = "telescope",
    EXT_SHELF = "shelf",
    EXT_SHELFPLAT = "shelfPlat",
    EXT_PILLAR = "pillar",
    EXT_TUBE = "truba",
    EXT_TREMPEL = "trempel",
    EXT_STAND = "stand",
    EXT_CONSOLE = "console",
    EXT_BLINDER = "blinder",
    EXT_LIGHT = "light"
}

export enum FASAD_SPECS {
    DSP = "DSP",
    MIRROR = "MIRROR",
    LACOBEL = "LACOBEL",
    FMP = "FMP",
    SAND = "SAND"
}
export const FasadSpecById: FASAD_SPECS[] = [FASAD_SPECS.DSP, FASAD_SPECS.MIRROR, FASAD_SPECS.LACOBEL, FASAD_SPECS.FMP, FASAD_SPECS.SAND]

export type SPEC_GROUP = FASAD_SPECS | CORPUS_SPECS;

